on:
  issues:
    types: [opened]

jobs:
  game:
    name: Wild Guess
    runs-on: ubuntu-latest

    outputs:
      code: ${{ steps.set-code.outputs.code }}

    if: startsWith(github.event.issue.title, 'And I guess (0-9):')

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set env vars
        run: |
            echo "USERNAME=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
            echo "ISSUE_TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV

      - name: Updating README.md
        id: set-code
        run: |
            echo "$ISSUE_TITLE $USERNAME"
            he=$(bash scripts/game.sh "$ISSUE_TITLE" "$USERNAME")
            echo $he
            echo "code=$he" >> $GITHUB_OUTPUT

  if-failed:
    name: Entered NaN
    needs: game
    runs-on: ubuntu-latest

    if: ${{ needs.game.outputs.code == 'failed' }}

    steps:
      - uses: actions/checkout@v3

      - name: Update Issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            You entered NaN â˜ ï¸,
            Please enter a number between 0 and 9, refer above.

      - name: Close Issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          state: 'closed'
          labels: 'guessed NaN,wild guess'

  if-missed-it:
    name: You Missed It
    needs: game
    runs-on: ubuntu-latest

    if: ${{ needs.game.outputs.code == 'missed-it' }}

    steps:
      - uses: actions/checkout@v3

      - name: Update Issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            You Missed It ğŸ¥º,
            Better luck next time ğŸ˜Š.

      - name: Close Issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          state: 'closed'
          labels: 'you missed it,wild guess'

  if-got-it:
    name: You Got It
    needs: game
    runs-on: ubuntu-latest

    if: ${{ needs.game.outputs.code == 'got-it' }}

    steps:
      - uses: actions/checkout@v3

      - name: Update Comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: You Got it, Hurray!! ğŸ¥³ğŸ¥³.

      - name: Close Comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'update-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          state: 'closed'
          labels: 'got it,wild guess'